### ISSUE TITLE
Mainnet Contracts Appear when Using Testnet and Vice-Versa

### ISSUE THREAD

**Issue by outragedhuman** [ubiq/fusion#3]
#### System information
``````
Version: 0.8.9
OS & Version: all
Node type: gubiq
``````

When using the testnet after adding contracts to the mainnet wallet, the mainnet contracts appear in the testnet wallet. 
 
![image](https://cloud.githubusercontent.com/assets/6742283/25286185/dc2f4a6a-268a-11e7-8ca6-ca6633f46c93.png)

Expected: When switching to testnet, the wallet should only pull in contracts which are for the testnet. 

NOTE: This same behavior occurs if you create a contract on testnet. Switching back to mainnet the testnet contract will be displayed.

**Comment by ob7** [comment]
It depends on what account made the contract.  And even then, contracts are not linked to accounts directly per see, but they are owned by a normal account.  When you import a ubiq wallet into fusion, it doesn't automatically add all of the contracts associated with it.  You would manually add the contract back into ubiq using the contract address.

So perhaps, you are seeing contracts in your wallet on both testnet and mainnet because they are contracts fusion is aware of, regardless of who owns them?  Whether or not you can execute the contract is the question.  Have you tried executing the contract owned by a mainnet address using a testnet owner, or vis versa?

**Comment by jyap808** [comment]
Stale issue. Not an issue.
