### ISSUE TITLE
Can't backup / restore contract easily

### ISSUE THREAD

**Issue by CreamyG31337** [ubiq/fusion#34]
- [x ] I've asked for help in the [Ubiq  Discord](https://discord.gg/HF6vEGF) before filing this issue.
```
Version: `0.9.2`
OS & Version: windows 10
Node version: `gubiq 1.5.12`
Number of blocks synchronized: 346725
```
After backing up and restoring the keystore to another copy of fusion, the wallet contract I created to receive payments is missing.
It seems like I'm supposed to also backup and restore something from the 'application data', but with no instructions, I'm not going to try to guess what. I do NOT want to copy the blockchain or any cache to the new install because of other issues I'm experiencing.

I tried, as a workaround, to add back my wallet as a contract to watch, but that doesn't work properly either. It doesn't recognize the contract as a wallet, and even though it shows a balance, I'm unable to send from it, nor is it counted towards the total account balance as it should be.

**Comment by ob7** [comment]
Your etherebase must have atleast a couple ubiq available in order to execute commands on a contract because the contract needs to get its gas from somewhere, and that somewhere is the etherbase account that owns it.

If you add a contract back to ubiq ( as a way of restoring it ), and your etherbase account is the owner, then you should be able to have full control of the contract granted your etherbase has some funds available to provide gas.

To restore a contract, you just need the address.  Make sure your etherbase has more than a zero balance and you should be able to execute on the contract. 

Let me know if you still have any trouble.

**Comment by CreamyG31337** [comment]
I think it's technically restored but Fusion doesn't recognize it as a 'wallet' so it isn't bothering to add the balance to my total (just a cosmetic display issue) or let me send from it (more of a headache) like it does on the original instance of Fusion.
